### ISSUE TITLE
Something doesn't look right in package.json

### ISSUE THREAD

**Issue by JakeChampion** [markdowncss/markdowncss.github.io#1]
I just came across your project from looking at immutable-css, good work on these projects!
In the `package.json` of this project there seems to be something funny happening on [line 7](https://github.com/markdowncss/markdowncss.github.io/blob/master/package.json#L7).

Good job on all these packages by the way!

**Comment by johno** [comment]
Yikes! That shouldn't be there. Thanks for reporting : )

Glad you like these packages!
